- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/SUPPORT.md
- .github/dependabot.yml
- .github/workflows/phpcs-check.yml
> TMS-491-1: Add .github config

- assets/styles/theme-sara_hilden.scss
- assets/styles/ui-components/_button.scss
- assets/styles/ui-components/_footer.scss
- assets/styles/ui-components/index.scss
- lib/ThemeController.php
- lib/ThemeCustomizationController.php
- package-lock.json
- partials/shared/footer-column.dust
> TMS-495: Footer styles

- CHANGELOG.MD
- assets/styles/ui-components/_breadcrumbs.scss
- assets/styles/ui-components/index.scss
> TMS-494: Breadcrumbs

- CHANGELOG.MD
- assets/styles/layouts/_text-block.scss
- assets/styles/layouts/index.scss
- assets/styles/main.scss
Text block layout styles.
TMS-537
locally
> TMS-537: Text block style fixes

- CHANGELOG.MD
- partials/layouts/layout-logo-wall.dust
Fix logo wall's colors by overriding partial and changing colors by classes.
TMS-512
Locally
> TMS-512: Logo wall layout's colors

- CHANGELOG.MD
- assets/styles/ui-components/_modal.scss
- assets/styles/ui-components/index.scss
- partials/ui/image/image-block__meta.dust
Image styling
TMS-511
Locally, staging
> TMS-511-3: Image

- CHANGELOG.MD
- assets/styles/blocks/_image-gallery.scss
- assets/styles/blocks/index.scss
- assets/styles/main.scss
- assets/styles/ui-components/_sibling-navigation.scss
- lib/ACF/AlterImageGalleryFields.php
Styling of Image Gallery
TMS-530
Locally, staging.
> TMS-530: Image Gallery

- CHANGELOG.MD
- assets/styles/settings/brand/_typography.scss
Classes for aligning text with editors text align options
TMS-537
Locally, staging
> TMS-537-2: Text paragraph

- CHANGELOG.MD
- lib/ACF/AlterContentColumnsFields.php
Removed display_artist field, because selection did nothing.
TMS-528
Locally, staging
> TMS-528-2: Content Columns Fields

- CHANGELOG.MD
- assets/styles/ui-components/_button.scss
- assets/styles/ui-components/_sitemap.scss
- assets/styles/ui-components/index.scss
Fixes to dropdown btn styles and styles in mobile
TMS-538
Local, staging
> TMS-538: Sitemap

- CHANGELOG.MD
- assets/styles/blocks/_contacts.scss
- assets/styles/blocks/index.scss
- assets/styles/main.scss
- partials/blocks/block-contacts.dust
- partials/shared/contact.dust
Style fixes for Contacts block. 
TMS-533
Local, staging
> TMS-533: Contacts block

- CHANGELOG.MD
- assets/styles/blocks/_table.scss
- assets/styles/blocks/index.scss
- assets/styles/main.scss
> TMS-523: Table styles

- CHANGELOG.MD
- assets/styles/ui-components/_button.scss
- lib/ACF/AlterImageBannerFields.php
- partials/blocks/block-image-banner.dust
Image banner's aspect ratio change, button icon, align works now also in mobile, styling
TMS-535
> TMS-535: Image banner

- CHANGELOG.MD
- assets/styles/layouts/_image-carousel.scss
- assets/styles/layouts/index.scss
- assets/styles/ui-components/_button.scss
- partials/layouts/layout-image-carousel.dust
Fixed image carousel styles and markup. Translations done in base theme, related branch also TMS-515
TMS-515
Locally, staging.
> TMS-515: Image carousel

- CHANGELOG.MD
- partials/layouts/layout-social-media.dust
SoMe embed styles and skip link for screen readers
TMS-256
Local, staging
> TMS-526: Social media embed

- CHANGELOG.MD
- assets/styles/ui-components/_share-links.scss
- assets/styles/ui-components/index.scss
- partials/ui/share-links.dust
SoMe share links styling
TMS-532
Local, staging
> TMS-532: Share in social media links

- CHANGELOG.MD
- partials/blocks/block-link-list.dust
Link list styling with partial and classes
TMS-524
Local, staging
> TMS-524: Link list

- CHANGELOG.MD
- assets/styles/layouts/_hero.scss
- assets/styles/layouts/index.scss
- lib/ACF/AlterHeroLayoutFields.php
- lib/Formatters/HeroFormatter.php
- partials/layouts/layout-hero.dust
Hero layout styling.
TMS-509
Local, staging
> TMS-509: Hero layout on front page

- CHANGELOG.MD
- lib/ACF/AlterCallToActionFields.php
Show image metadata option removed
TMS-519
local, staging
> TMS-519: Call to action layout

- CHANGELOG.MD
- lib/ACF/AlterMaterialBlockData.php
Material block styles
TMS-503
Local, staging
> TMS-503: Material block

- CHANGELOG.MD
- assets/styles/blocks/_accordion.scss
- assets/styles/blocks/_table.scss
- assets/styles/blocks/index.scss
- partials/blocks/block-accordion.dust
Accordion styles. Table styles. This PR is related to base theme's PR https://github.com/devgeniem/tms-theme-base/pull/341/ 
TMS-522
Local, staging
> TMS-522: Accordion, indicate in tables

- CHANGELOG.MD
- partials/views/home/home-grid-item.dust
- partials/views/home/home-highlight.dust
Whole article highlight as a link
TMS-518
Local, staging
> TMS-518: Artcle highlights

- CHANGELOG.MD
- assets/styles/ui-components/header/_site-header-notice.scss
- assets/styles/ui-components/index.scss
Header notice styles.
TMS-517
Local, staging
> TMS-517: Header notice

- lib/PostType/Artist.php
- lib/PostType/Artwork.php
- models/page-artwork.php
- models/single-artwork.php
Fix an issue where link to current artist is not present, if the current artwork is the artists' only artwork.
TMS-430
> TMS-430: Fix related artwork logic

- CHANGELOG.MD
- models/single-artwork.php
> TMS-728: Fix media gallery texts of featured image in artwork.

- CHANGELOG.MD
- lib/ThemeCustomizationController.php
Add filter for custom links removal.
TMS-771
Local, stage.
> TMS-771: Overwrite custom links removal via filter

- CHANGELOG.MD
- models/page-artist.php
Fix query on PageArtist model.
TMS-776
Local, stage.
> TMS-776: Fix query on PageArtist model

- CHANGELOG.MD
- assets/styles/ui-components/_footer.scss
Set the footer logo max-height.
TMS-773
Local, stage.
> TMS-773: Set the footer logo max-height

- CHANGELOG.MD
- partials/ui/image/image-block__meta.dust
Changed the image block meta data layout
TMS-774
Local, stage.
> TMS-774: Changed the image block meta data layout

- CHANGELOG.MD
- assets/styles/ui-components/_footer.scss
Remove automatic hyphenation from headings in footer
TMS-775
Local, stage.
> TMS-775: Remove automatic hyphenation from headings in footer

- CHANGELOG.MD
- partials/blocks/block-contacts.dust
- partials/shared/contact.dust
Contact headings align left, spacing adjusted accordingly
TMS-806
Local
> TMS-806: Contact headings align left

- CHANGELOG.MD
- assets/styles/blocks/_accordion.scss
- assets/styles/blocks/_image.scss
- assets/styles/blocks/index.scss
- assets/styles/settings/_settings.scss
- assets/styles/views/_single-artist.scss
- assets/styles/views/_single-artwork.scss
- assets/styles/views/_single.scss
- assets/styles/views/index.scss
- partials/layouts/layout-accordion-image.dust
- partials/layouts/layout-content-columns.dust
- partials/shared/artwork-list.dust
- partials/single-artist.dust
- partials/single-artwork.dust
- partials/single.dust
CR: https://geniemdev.atlassian.net/browse/TMS-808
Retain the original image ratio on:
- Layout content columns
- Layout accordion image
- Single artist and artwork images
- Single post featured image
TMS-808
Local, stage.
> TMS-808: Retain the original image ratio

- CHANGELOG.MD
- assets/styles/layouts/_hero.scss
- lib/ACF/AlterHeroLayoutFields.php
Bigger font size on front page hero's title.
TMS-811
Local, stage.
> TMS-811: Font size on front page hero title changed

- CHANGELOG.MD
- models/single-artwork.php
- partials/single-artwork.dust
Display image meta in single artwork view
TMS-816
> TMS-816: Display image meta in single artwork view

- CHANGELOG.MD
- partials/shared/exhibition-item.dust
Fix Exhibition upcoming sr-text visibility and add missing escapes.
TMS-812
> TMS-812: Fix Exhibition upcoming sr-text visibility

- CHANGELOG.MD
- lib/PostType/Artist.php
- lib/PostType/Artwork.php
- lib/PostType/Exhibition.php
> TMS-813: Translate CPT name

- CHANGELOG.MD
- partials/views/home/home-highlight.dust
CR: https://geniemdev.atlassian.net/browse/PIEN-7610
> PIEN-7610: Fix showing images from API

- CHANGELOG.MD
- models/single-exhibition.php
- style.css
CR: https://geniemdev.atlassian.net/browse/PIEN-8493
Fix illegal offset type in single-exhibition that caused a fatal error
> PIEN-8493: Fix illegal offset type in foreach

- CHANGELOG.MD
- models/single.php
CR: PIEN-8524
Display API images in related articles
PIEN-8524
> PIEN-8524: Display API images

- CHANGELOG.MD
- partials/layouts/layout-image-carousel.dust
- style.css
Task: https://hiondigital.atlassian.net/browse/TMS-936
Image carousel layout accessibility fixes
> TMS-936: Image carousel accessibility fixes

- CHANGELOG.MD
- partials/layouts/layout-content-columns.dust
Task: https://hiondigital.atlassian.net/browse/TMS-970
Add image meta to content-columns component
> TMS-970: Add image meta to content-columns component

- CHANGELOG.MD
- assets/styles/layouts/_image-carousel.scss
- style.css
Severa-ID: 2247
Severa-kuvaus: TMS-1021 Kuvakarusellin vaakakuvien asemointi
Task: https://hiondigital.atlassian.net/browse/TMS-1021
Remove max-height to prevent modal alignment problems with tms-theme-base fix
> TMS-1021: Remove image carousel modal max-height

- CHANGELOG.MD
- assets/styles/ui-components/_footer.scss
- style.css
Severa-kuvaus: TMS-1028 Uusi elementti: somelinkkilista
Task: https://hiondigital.atlassian.net/browse/TMS-1028
Fix footer social-media icon color
> TMS-1028: Fix footer social-media icon color

- CHANGELOG.MD
- partials/blocks/block-accordion.dust
Severa-kuvaus: TMS-1044 Haitarilohkoon kehitystä
Task: https://hiondigital.atlassian.net/browse/TMS-1044
- Add open & close buttons and icon-texts to accordion partial
> TMS-1044: Add open & close buttons and icon-texts to accordion partial

- lib/ACF/AlterHeroLayoutFields.php
Fix changed video-field key to the proper one
> Fix hero field key

- CHANGELOG.MD
- lib/PostType/Artwork.php
Severa-kuvaus: TMS-1075 Redipress 2 päivitys
Task: https://hiondigital.atlassian.net/browse/TMS-1075
Filter changes for Redipress 2 update
> TMS-1075: Redipress 2 filters

- CHANGELOG.MD
- partials/blocks/block-accordion.dust
Severa-kuvaus: TMS-1091 Haitari-lohkon pieni tyylimuutos
Task: https://hiondigital.atlassian.net/browse/TMS-1091
Remove align-wide class from accordion block
> TMS-1091: Remove align-wide class from accordion block

- CHANGELOG.MD
- lib/ACF/AlterCallToActionFields.php
- lib/ACF/AlterContentColumnsFields.php
- partials/layouts/layout-content-columns.dust
- partials/ui/image/image-meta-minimal.dust
Severa-kuvaus: TMS-1114 Kuvaaja-tiedot näkyviin myös Palstat-komponenttiin
Task: https://hiondigital.atlassian.net/browse/TMS-1114
Change image-meta on cta- & content-columns components
> TMS-1114: Change image-meta on cta- & content-columns components

- CHANGELOG.MD
- assets/styles/views/_page-events.scss
Severa-ID: 2247
Severa-kuvaus: TMS-1131 Tapahtumahaku-sivupohjan hakusana-kentästä puuttuu reunat
Task: https://hiondigital.atlassian.net/browse/TMS-1131
Fix event search form styles, modify duet-datepicker style overrides
> TMS-1131: Events search form style changes

- CHANGELOG.MD
- assets/styles/layouts/_hero.scss
- lib/ACF/AlterHeroLayoutFields.php
- partials/layouts/layout-hero.dust
Severa-kuvaus: TMS-1172 Kehitystä heron videoon, tietyt teemat
Task: https://hiondigital.atlassian.net/browse/TMS-1172
Add video-possibility to hero-layout
> TMS-1172: Add video-fields and functionality to hero-component
